[project]
name = "pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.6.15"
dependencies = [
    "celery>=5.1.2",
    "invoke>=2.2.1",
    "langchain>=0.0.27",
    "pypdf>=5.0.0",
    "watchdog>=2.3.1",
]
